### ISSUE TITLE
Support debug option.

### ISSUE THREAD

**Issue by SamMousa** [grantlucas/phantoman#54]
Currently debug is only used to dump the generated command. 
It would make sense to also pass this on to phantomJS.

**Comment by cewald** [comment]
You can use my fork until the pull request might be accepted.
Use the option ```webdriverLoglevel: 'debug'``` to see all console messages.

Fork: https://github.com/cewald/phantoman
Pull request: #55

**Comment by grantlucas** [comment]
Hi there! Would the features added in PR #55 resolve this issue for you or is the PhantomJS debug option still needed? Thanks!

**Comment by grantlucas** [comment]
Should be fixed by #55
