### ISSUE TITLE
Phantom cannot run on https without valid certificate

### ISSUE THREAD

**Issue by rebas82** [grantlucas/phantoman#56]
When i go in test to website with https and certificate for domain isnt valid, test cannot go and write many errors. (phantomjs).

When i visit same website with Selenium, test continue normaly.

**Comment by grantlucas** [comment]
Please be sure to set `ignoreSslErrors: true` in your Phantoman config in Codeception.yml. This should resolve this issue (_Very_ sorry for not getting to this sooner)
