### ISSUE TITLE
loadImages option incorrectly defined

### ISSUE THREAD

**Issue by awhale** [grantlucas/phantoman#60]
The loadImages configuration option, when used as documented does not work. 

The option is documented as:

> loadImages: {true|false}

which does not match the definition in the source:

https://github.com/grantlucas/phantoman/blob/ba45e83c1f3ee4021a649ca097fa6a969d00e729/src/Phantoman.php#L244

**Comment by grantlucas** [comment]
good catch! Thanks. I'll tag a new release with the fix.

**Comment by grantlucas** [comment]
Should be good to go with `v2.0.1`
